//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ResultsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ResultsService.IResults")]
    public interface IResults {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/Get", ReplyAction="http://tempuri.org/IResults/GetResponse")]
        ApplicationService.DTOs.ResultDTO[] Get();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/Get", ReplyAction="http://tempuri.org/IResults/GetResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResults", ReplyAction="http://tempuri.org/IResults/GetResultsResponse")]
        ApplicationService.DTOs.ResultDTO[] GetResults();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResults", ReplyAction="http://tempuri.org/IResults/GetResultsResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsForAthleteById", ReplyAction="http://tempuri.org/IResults/GetResultsForAthleteByIdResponse")]
        ApplicationService.DTOs.ResultDTO[] GetResultsForAthleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsForAthleteById", ReplyAction="http://tempuri.org/IResults/GetResultsForAthleteByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsForAthleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsById", ReplyAction="http://tempuri.org/IResults/GetResultsByIdResponse")]
        ApplicationService.DTOs.ResultDTO GetResultsById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsById", ReplyAction="http://tempuri.org/IResults/GetResultsByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO> GetResultsByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/UpdateResult", ReplyAction="http://tempuri.org/IResults/UpdateResultResponse")]
        string UpdateResult(ApplicationService.DTOs.ResultDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/UpdateResult", ReplyAction="http://tempuri.org/IResults/UpdateResultResponse")]
        System.Threading.Tasks.Task<string> UpdateResultAsync(ApplicationService.DTOs.ResultDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/DeleteResult", ReplyAction="http://tempuri.org/IResults/DeleteResultResponse")]
        string DeleteResult(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/DeleteResult", ReplyAction="http://tempuri.org/IResults/DeleteResultResponse")]
        System.Threading.Tasks.Task<string> DeleteResultAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/PostResult", ReplyAction="http://tempuri.org/IResults/PostResultResponse")]
        string PostResult(ApplicationService.DTOs.ResultDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/PostResult", ReplyAction="http://tempuri.org/IResults/PostResultResponse")]
        System.Threading.Tasks.Task<string> PostResultAsync(ApplicationService.DTOs.ResultDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsByEventName", ReplyAction="http://tempuri.org/IResults/GetResultsByEventNameResponse")]
        ApplicationService.DTOs.ResultDTO[] GetResultsByEventName(string eventName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IResults/GetResultsByEventName", ReplyAction="http://tempuri.org/IResults/GetResultsByEventNameResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsByEventNameAsync(string eventName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IResultsChannel : MVC.ResultsService.IResults, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ResultsClient : System.ServiceModel.ClientBase<MVC.ResultsService.IResults>, MVC.ResultsService.IResults {
        
        public ResultsClient() {
        }
        
        public ResultsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ResultsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ResultsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.ResultDTO[] Get() {
            return base.Channel.Get();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetAsync() {
            return base.Channel.GetAsync();
        }
        
        public ApplicationService.DTOs.ResultDTO[] GetResults() {
            return base.Channel.GetResults();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsAsync() {
            return base.Channel.GetResultsAsync();
        }
        
        public ApplicationService.DTOs.ResultDTO[] GetResultsForAthleteById(int id) {
            return base.Channel.GetResultsForAthleteById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsForAthleteByIdAsync(int id) {
            return base.Channel.GetResultsForAthleteByIdAsync(id);
        }
        
        public ApplicationService.DTOs.ResultDTO GetResultsById(int id) {
            return base.Channel.GetResultsById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO> GetResultsByIdAsync(int id) {
            return base.Channel.GetResultsByIdAsync(id);
        }
        
        public string UpdateResult(ApplicationService.DTOs.ResultDTO item) {
            return base.Channel.UpdateResult(item);
        }
        
        public System.Threading.Tasks.Task<string> UpdateResultAsync(ApplicationService.DTOs.ResultDTO item) {
            return base.Channel.UpdateResultAsync(item);
        }
        
        public string DeleteResult(int id) {
            return base.Channel.DeleteResult(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteResultAsync(int id) {
            return base.Channel.DeleteResultAsync(id);
        }
        
        public string PostResult(ApplicationService.DTOs.ResultDTO item) {
            return base.Channel.PostResult(item);
        }
        
        public System.Threading.Tasks.Task<string> PostResultAsync(ApplicationService.DTOs.ResultDTO item) {
            return base.Channel.PostResultAsync(item);
        }
        
        public ApplicationService.DTOs.ResultDTO[] GetResultsByEventName(string eventName) {
            return base.Channel.GetResultsByEventName(eventName);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.ResultDTO[]> GetResultsByEventNameAsync(string eventName) {
            return base.Channel.GetResultsByEventNameAsync(eventName);
        }
    }
}
