//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.GamesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GamesService.IGames")]
    public interface IGames {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGames", ReplyAction="http://tempuri.org/IGames/GetGamesResponse")]
        ApplicationService.DTOs.GameDTO[] GetGames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGames", ReplyAction="http://tempuri.org/IGames/GetGamesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/PostGame", ReplyAction="http://tempuri.org/IGames/PostGameResponse")]
        string PostGame(ApplicationService.DTOs.GameDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/PostGame", ReplyAction="http://tempuri.org/IGames/PostGameResponse")]
        System.Threading.Tasks.Task<string> PostGameAsync(ApplicationService.DTOs.GameDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGameById", ReplyAction="http://tempuri.org/IGames/GetGameByIdResponse")]
        ApplicationService.DTOs.GameDTO GetGameById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGameById", ReplyAction="http://tempuri.org/IGames/GetGameByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO> GetGameByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/UpdateGame", ReplyAction="http://tempuri.org/IGames/UpdateGameResponse")]
        string UpdateGame(ApplicationService.DTOs.GameDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/UpdateGame", ReplyAction="http://tempuri.org/IGames/UpdateGameResponse")]
        System.Threading.Tasks.Task<string> UpdateGameAsync(ApplicationService.DTOs.GameDTO item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/DeleteGame", ReplyAction="http://tempuri.org/IGames/DeleteGameResponse")]
        string DeleteGame(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/DeleteGame", ReplyAction="http://tempuri.org/IGames/DeleteGameResponse")]
        System.Threading.Tasks.Task<string> DeleteGameAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGameByTitle", ReplyAction="http://tempuri.org/IGames/GetGameByTitleResponse")]
        ApplicationService.DTOs.GameDTO[] GetGameByTitle(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGames/GetGameByTitle", ReplyAction="http://tempuri.org/IGames/GetGameByTitleResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGameByTitleAsync(string title);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamesChannel : MVC.GamesService.IGames, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamesClient : System.ServiceModel.ClientBase<MVC.GamesService.IGames>, MVC.GamesService.IGames {
        
        public GamesClient() {
        }
        
        public GamesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GamesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.GameDTO[] GetGames() {
            return base.Channel.GetGames();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGamesAsync() {
            return base.Channel.GetGamesAsync();
        }
        
        public string PostGame(ApplicationService.DTOs.GameDTO item) {
            return base.Channel.PostGame(item);
        }
        
        public System.Threading.Tasks.Task<string> PostGameAsync(ApplicationService.DTOs.GameDTO item) {
            return base.Channel.PostGameAsync(item);
        }
        
        public ApplicationService.DTOs.GameDTO GetGameById(int id) {
            return base.Channel.GetGameById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO> GetGameByIdAsync(int id) {
            return base.Channel.GetGameByIdAsync(id);
        }
        
        public string UpdateGame(ApplicationService.DTOs.GameDTO item) {
            return base.Channel.UpdateGame(item);
        }
        
        public System.Threading.Tasks.Task<string> UpdateGameAsync(ApplicationService.DTOs.GameDTO item) {
            return base.Channel.UpdateGameAsync(item);
        }
        
        public string DeleteGame(int id) {
            return base.Channel.DeleteGame(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteGameAsync(int id) {
            return base.Channel.DeleteGameAsync(id);
        }
        
        public ApplicationService.DTOs.GameDTO[] GetGameByTitle(string title) {
            return base.Channel.GetGameByTitle(title);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.GameDTO[]> GetGameByTitleAsync(string title) {
            return base.Channel.GetGameByTitleAsync(title);
        }
    }
}
