//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.AthletesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AthletesService.IAthletes")]
    public interface IAthletes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthletes", ReplyAction="http://tempuri.org/IAthletes/GetAthletesResponse")]
        ApplicationService.DTOs.AthleteDTO[] GetAthletes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthletes", ReplyAction="http://tempuri.org/IAthletes/GetAthletesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO[]> GetAthletesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthleteById", ReplyAction="http://tempuri.org/IAthletes/GetAthleteByIdResponse")]
        ApplicationService.DTOs.AthleteDTO GetAthleteById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthleteById", ReplyAction="http://tempuri.org/IAthletes/GetAthleteByIdResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO> GetAthleteByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/PostAthlete", ReplyAction="http://tempuri.org/IAthletes/PostAthleteResponse")]
        string PostAthlete(ApplicationService.DTOs.AthleteDTO athleteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/PostAthlete", ReplyAction="http://tempuri.org/IAthletes/PostAthleteResponse")]
        System.Threading.Tasks.Task<string> PostAthleteAsync(ApplicationService.DTOs.AthleteDTO athleteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/DeleteAthlete", ReplyAction="http://tempuri.org/IAthletes/DeleteAthleteResponse")]
        string DeleteAthlete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/DeleteAthlete", ReplyAction="http://tempuri.org/IAthletes/DeleteAthleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAthleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/UpdateAthlete", ReplyAction="http://tempuri.org/IAthletes/UpdateAthleteResponse")]
        string UpdateAthlete(ApplicationService.DTOs.AthleteDTO athleteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/UpdateAthlete", ReplyAction="http://tempuri.org/IAthletes/UpdateAthleteResponse")]
        System.Threading.Tasks.Task<string> UpdateAthleteAsync(ApplicationService.DTOs.AthleteDTO athleteDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthletesByName", ReplyAction="http://tempuri.org/IAthletes/GetAthletesByNameResponse")]
        ApplicationService.DTOs.AthleteDTO[] GetAthletesByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAthletes/GetAthletesByName", ReplyAction="http://tempuri.org/IAthletes/GetAthletesByNameResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO[]> GetAthletesByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAthletesChannel : MVC.AthletesService.IAthletes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AthletesClient : System.ServiceModel.ClientBase<MVC.AthletesService.IAthletes>, MVC.AthletesService.IAthletes {
        
        public AthletesClient() {
        }
        
        public AthletesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AthletesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AthletesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AthletesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ApplicationService.DTOs.AthleteDTO[] GetAthletes() {
            return base.Channel.GetAthletes();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO[]> GetAthletesAsync() {
            return base.Channel.GetAthletesAsync();
        }
        
        public ApplicationService.DTOs.AthleteDTO GetAthleteById(int id) {
            return base.Channel.GetAthleteById(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO> GetAthleteByIdAsync(int id) {
            return base.Channel.GetAthleteByIdAsync(id);
        }
        
        public string PostAthlete(ApplicationService.DTOs.AthleteDTO athleteDTO) {
            return base.Channel.PostAthlete(athleteDTO);
        }
        
        public System.Threading.Tasks.Task<string> PostAthleteAsync(ApplicationService.DTOs.AthleteDTO athleteDTO) {
            return base.Channel.PostAthleteAsync(athleteDTO);
        }
        
        public string DeleteAthlete(int id) {
            return base.Channel.DeleteAthlete(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAthleteAsync(int id) {
            return base.Channel.DeleteAthleteAsync(id);
        }
        
        public string UpdateAthlete(ApplicationService.DTOs.AthleteDTO athleteDTO) {
            return base.Channel.UpdateAthlete(athleteDTO);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAthleteAsync(ApplicationService.DTOs.AthleteDTO athleteDTO) {
            return base.Channel.UpdateAthleteAsync(athleteDTO);
        }
        
        public ApplicationService.DTOs.AthleteDTO[] GetAthletesByName(string name) {
            return base.Channel.GetAthletesByName(name);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.AthleteDTO[]> GetAthletesByNameAsync(string name) {
            return base.Channel.GetAthletesByNameAsync(name);
        }
    }
}
